name: handygenome
dependencies:
    - python
    - conda-forge::psutil

    - conda-forge::jupyterlab
    - conda-forge::ipykernel

    - conda-forge::numpy
    - conda-forge::scipy
    - conda-forge::scikit-learn
    - conda-forge::pandas
    - conda-forge::matplotlib
    - conda-forge::seaborn
    - conda-forge::biopython>=1.80
    - bioconda::pysam
    - bioconda::pyranges
    #- bioconda::pybigwig
