---
bash: "/usr/bin/bash"
perl: "/home/users/pjh/scripts/conda_wrapper/perl"
python: null #"/home/users/pjh/tools/miniconda/221104/miniconda3/envs/genome_v7/bin/python"
vep: "/home/users/pjh/scripts/conda_wrapper/vep_v105"
vep_mm10: "/home/users/pjh/scripts/conda_wrapper/vep_v102" # for mm10
vep_cache_dir: "/home/users/pjh/.vep"

default_refver: 'human'

refverinfo:
    ## Most of reference versions are derived from RefSeq ftp

    # Homo sapiens
    - 
        standard: "T2T-CHM13v2"
        aliases: []
        parent_standard: "T2T-CHM13v2"
        fasta_path: null
        species: "Homo_sapiens"
    - 
        standard: "GRCh38"
        aliases: ["hg38", "grch38"]
        parent_standard: "GRCh38"
        fasta_path: "/home/users/data/01_reference/human_g1k_v38/Homo_sapiens_assembly38.fasta"
        species: "Homo_sapiens"

        edited_repeat_path: "/home/users/pjh/References/ucsc_data_files/modified_files/grch38/repeatmasker.bed.gz"
        edited_geneset_path: "/home/users/pjh/References/ensembl_data_files/modified_files/grch38/geneset_gff3_sorted.gz"
        edited_regulatory_path: "/home/users/pjh/References/ensembl_data_files/modified_files/grch38/ensembl_regulatory_sorted.grch38.gff.gz"
    - 
        standard: "GRCh37"
        aliases: ["hg19", "grch37"]
        parent_standard: "GRCh37"
        fasta_path: null
        species: "Homo_sapiens"
    - 
        standard: "GRCh37_1kg"
        aliases: ['human']
        parent_standard: "GRCh37"
        fasta_path: "/home/users/data/01_reference/human_g1k_v37/human_g1k_v37.fasta"
        species: "Homo_sapiens"

        edited_repeat_path: "/home/users/pjh/References/ucsc_data_files/modified_files/grch37/repeatmasker.bed.gz"
        edited_geneset_path: "/home/users/pjh/References/ensembl_data_files/modified_files/grch37/geneset_gff3_sorted.gz"
        edited_regulatory_path: "/home/users/pjh/References/ensembl_data_files/modified_files/grch37/ensembl_regulatory_sorted.grch37.gff.gz"
    - 
        standard: "GRCh37_hs37d5"
        aliases: []
        parent_standard: "GRCh37"
        fasta_path: "/home/users/sypark/02_Reference/15_pcawg/genome.fa"
        species: "Homo_sapiens"
    - 
        standard: "NCBI36"
        aliases: ["hg18", "ncbi36"]
        parent_standard: "NCBI36"
        fasta_path: "/home/users/pjh/References/reference_genome/NCBI36/ucsc/custom_files/hg18.fa"
        species: "Homo_sapiens"
    - 
        standard: "NCBI35"
        aliases: []
        parent_standard: "NCBI35"
        fasta_path: null
        species: "Homo_sapiens"
    - 
        standard: "NCBI34"
        aliases: []
        parent_standard: "NCBI34"
        fasta_path: null
        species: "Homo_sapiens"
    - 
        standard: "NCBI33"
        aliases: []
        parent_standard: "NCBI33"
        fasta_path: null
        species: "Homo_sapiens"
    
    # Mus musculus
    - 
        standard: "GRCm39"
        aliases: ["mm39", "grcm39"]
        parent_standard: "GRCm39"
        fasta_path: "/home/users/pjh/References/reference_genome/GRCm39/ucsc/custom_files/mm39.fa"
        species: "Mus_musculus"
    - 
        standard: "GRCm38"
        aliases: ["mm10", "grcm38"]
        parent_standard: "GRCm38"
        fasta_path: "/home/users/pjh/References/reference_genome/GRCm38/ucsc/custom_files/mm10.fa"
        species: "Mus_musculus"
    - 
        standard: "MGSCv37"
        aliases: ["mm9"]
        parent_standard: "MGSCv37"
        fasta_path: null
        species: "Mus_musculus"
    -
        standard: "MGSCv36"
        aliases: []
        parent_standard: "MGSCv36"
        fasta_path: null
        species: "Mus_musculus"
    -
        standard: "MGSCv35"
        aliases: []
        parent_standard: "MGSCv35"
        fasta_path: null
        species: "Mus_musculus"
    -
        standard: "MGSCv34"
        aliases: []
        parent_standard: "MGSCv34"
        fasta_path: null
        species: "Mus_musculus"
    -
        standard: "MGSCv3"
        aliases: []
        parent_standard: "MGSCv3"
        fasta_path: null
        species: "Mus_musculus"

    # Musa acuminata
    -
        standard: "DHPahang4"
        aliases: ["banana"]
        parent_standard: null
        fasta_path: "/home/users/yeonjin/practice/banana/reference/Musa_acuminata_pahang_v4_cp.fasta"
        species: "Musa_acuminata_malaccensis"
    -
        standard: "ASM31385v2"
        aliases: []
        parent_standard: "ASM31385v2"
        fasta_path: null
        species: "Musa_acuminata"
    -
        standard: "ASM31385v1"
        aliases: []
        parent_standard: "ASM31385v1"
        fasta_path: null
        species: "Musa_acuminata"


